### ISSUE TITLE
Big differences when drawing a map

### ISSUE THREAD

**Issue by Murdoc84** [mm3141/Terrain#3]
Big differences when drawing large maps, the larger the map, the bigger the difference, almost 1cm on 24inch display (screenshots). In the case of small maps, it is practically invisible.
![image](https://user-images.githubusercontent.com/22428605/87790594-17720800-c841-11ea-9a9f-94eb16f8b966.png)
![image](https://user-images.githubusercontent.com/22428605/87790613-1f31ac80-c841-11ea-86ac-1bfc28679bd8.png)

**Comment by mm3141** [comment]
I don't think this can be fixed easily, the underlying data used is 2D (missing Z), whereas the map outlines are based on 3D data.
